import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Gauge, Lightbulb, Radar, ShieldCheck } from "lucide-react";
import Navbar from "@/components/marketing/Navbar";
import Footer from "@/components/marketing/Footer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type FeatureDoc = {
  id: string;
  title: string;
  desc: string;
  advice: string;
};

type MetricDoc = {
  name: string;
  meaning: string;
  advice: string;
};

const EN = {
  pageTitle: "Product Documentation",
  pageDescription: "Public product documentation in English and Arabic. Learn every feature, metric meaning, and practical advice.",
  heroBadge: "Public Documentation",
  heroTitle: "How To Use EYE",
  heroSubtitle: "A complete, simple guide for all product functions, what each metric means, and how to take action.",
  noAuth: "This page is public and does not require authorization.",
  quickStartTitle: "Quick Start",
  quickStart: [
    "Create your domain in the dashboard.",
    "Install the tracker script on your website.",
    "Open the dashboard and verify first events are arriving.",
    "Use the period filter (7d/30d/90d) before reading trends.",
  ],
  featuresTitle: "All Main Functions",
  metricsTitle: "Metrics: What Numbers Mean",
  tipsTitle: "Operating Advice",
  adviceLabel: "Advice",
  metricNameLabel: "Name",
  metricMeaningLabel: "Meaning",
  metricAdviceLabel: "Advice",
  tips: [
    "Use one domain at a time when reading reports to avoid mixed interpretation.",
    "Compare 7-day and 30-day windows before making product decisions.",
    "Treat bounce rate and session duration together, not separately.",
    "Investigate pages with high traffic but low conversion first.",
  ],
  ctaTitle: "Need Account Access?",
  ctaText: "Documentation is public, but live analytics and configuration require account login.",
  ctaButton: "Create Free Account",
  features: [
    { id: "dashboard", title: "Dashboard Overview", desc: "See core KPIs: visitors, sessions, bounce rate, average session duration, and trend chart.", advice: "Use this as your daily health check. If visitors rise while conversion drops, inspect top pages and funnels." },
    { id: "realtime", title: "Realtime", desc: "Watch active visitors and live events as they happen.", advice: "Use during campaigns or launches to detect traffic quality issues quickly." },
    { id: "visitors", title: "Visitors", desc: "Explore individual visitors, session counts, locations, devices, and recent journey.", advice: "Segment by country/device to spot regional or device-specific friction." },
    { id: "pages", title: "Pages Analytics", desc: "Analyze top pages by views, unique visitors, and engagement signals.", advice: "Improve top entry pages first, because small gains there affect many sessions." },
    { id: "referrers", title: "Referrers", desc: "Measure where traffic comes from (search, social, direct, campaigns).", advice: "Double down on sources with high engagement, not just high volume." },
    { id: "funnels", title: "Funnel Builder", desc: "Create multi-step conversion funnels and identify where users drop off.", advice: "Fix one bottleneck step at a time, then measure again after deployment." },
    { id: "ux", title: "UX Intelligence", desc: "Review UX issues and quality scores to detect friction patterns.", advice: "Prioritize issues affecting key pages in your conversion path." },
    { id: "custom_events", title: "Custom Events", desc: "Track business-specific actions like signup_click, checkout_start, and form_submit.", advice: "Keep event names consistent and action-oriented to avoid reporting confusion." },
    { id: "identities", title: "Identities", desc: "Map anonymous activity to known user identities when available.", advice: "Connect identity after user consent and login for better lifecycle analysis." },
    { id: "companies", title: "Companies", desc: "View company-level traffic enrichment for B2B use cases.", advice: "Send high-intent company visits to sales follow-up workflows." },
    { id: "exports", title: "Exports", desc: "Export analytics datasets for offline analysis and sharing.", advice: "Use scheduled exports for recurring reports to avoid manual effort." },
    { id: "settings", title: "Settings", desc: "Manage profile, notifications, domains, security, and billing.", advice: "Enable 2FA for all admin users and keep webhook endpoints monitored." },
  ] as FeatureDoc[],
  metrics: [
    { name: "Visitors", meaning: "Unique visitor identifiers during the selected time period.", advice: "Growing visitors with stable quality usually indicates healthy acquisition." },
    { name: "Sessions", meaning: "Distinct visit sessions generated by users.", advice: "A strong visitors-to-sessions ratio can indicate repeat engagement." },
    { name: "Pageviews", meaning: "Total page view events captured.", advice: "Use alongside visitors to understand depth, not just reach." },
    { name: "Bounce Rate", meaning: "Percent of sessions with only one page view.", advice: "High bounce is not always bad; evaluate by page intent and traffic source." },
    { name: "Avg Session Duration", meaning: "Average time users spend in a session.", advice: "Validate against conversion outcomes; longer is not always better." },
    { name: "Top Pages", meaning: "Pages receiving the highest pageview volume.", advice: "Optimize these pages first for UX and conversion messaging." },
    { name: "Top Countries", meaning: "Geographic distribution of visitor activity.", advice: "Localize language and offers for top markets where possible." },
    { name: "Top Devices", meaning: "Traffic split by desktop, mobile, and tablet categories.", advice: "If mobile dominates, test forms and checkout flow on small screens first." },
  ] as MetricDoc[],
};

const AR = {
  pageTitle: "توثيق المنتج",
  pageDescription: "توثيق عام للمنتج بالإنجليزية والعربية يشرح كل الوظائف ومعاني الأرقام والنصائح العملية.",
  heroBadge: "توثيق عام",
  heroTitle: "كيفية استخدام EYE",
  heroSubtitle: "دليل كامل وبسيط لكل وظائف المنتج، ومعنى كل رقم، وكيف تتخذ قراراً عملياً.",
  noAuth: "هذه الصفحة عامة ويمكن الوصول إليها بدون تسجيل دخول.",
  quickStartTitle: "بداية سريعة",
  quickStart: [
    "أنشئ النطاق الخاص بك داخل لوحة التحكم.",
    "ثبّت سكريبت التتبع على موقعك.",
    "افتح لوحة التحكم وتأكد من وصول أول الأحداث.",
    "استخدم فلتر الفترة الزمنية (7 أيام/30 يوماً/90 يوماً) قبل قراءة الاتجاهات.",
  ],
  featuresTitle: "كل الوظائف الأساسية",
  metricsTitle: "المقاييس: ماذا تعني الأرقام",
  tipsTitle: "نصائح تشغيلية",
  adviceLabel: "نصيحة",
  metricNameLabel: "المقياس",
  metricMeaningLabel: "المعنى",
  metricAdviceLabel: "النصيحة",
  tips: [
    "حلل نطاقاً واحداً في كل مرة لتجنب خلط التفسير بين البيانات.",
    "قارن بين آخر 7 أيام وآخر 30 يوماً قبل أي قرار منتجي.",
    "اقرأ معدل الارتداد مع مدة الجلسة معاً وليس بشكل منفصل.",
    "ابدأ بالصفحات ذات الزيارات العالية والتحويل المنخفض.",
  ],
  ctaTitle: "تحتاج للدخول إلى الحساب؟",
  ctaText: "التوثيق متاح للجميع، لكن التحليلات المباشرة وإعدادات النظام تحتاج تسجيل دخول.",
  ctaButton: "إنشاء حساب مجاني",
  features: [
    { id: "dashboard", title: "نظرة عامة للوحة التحكم", desc: "عرض المؤشرات الأساسية: الزوار، الجلسات، معدل الارتداد، متوسط مدة الجلسة، ومخطط الاتجاه.", advice: "استخدمها كفحص يومي. إذا زاد الزوار وانخفض التحويل، راجع أفضل الصفحات والقمع." },
    { id: "realtime", title: "البيانات المباشرة", desc: "مراقبة الزوار النشطين والأحداث في الوقت الحقيقي.", advice: "مفيدة أثناء الحملات والإطلاق لاكتشاف مشاكل جودة الزيارات بسرعة." },
    { id: "visitors", title: "الزوار", desc: "استعراض كل زائر، عدد الجلسات، الموقع، الجهاز، والمسار الأخير.", advice: "قسّم حسب الدولة والجهاز لاكتشاف مشاكل خاصة بسوق أو جهاز معين." },
    { id: "pages", title: "تحليلات الصفحات", desc: "تحليل أفضل الصفحات حسب المشاهدات والزوار ومؤشرات التفاعل.", advice: "حسّن صفحات الدخول الأعلى أولاً لأن أي تحسين فيها يؤثر على عدد كبير من الجلسات." },
    { id: "referrers", title: "مصادر الزيارات", desc: "قياس مصدر الزيارات مثل البحث والسوشيال والزيارات المباشرة والحملات.", advice: "اعتمد أكثر على المصادر ذات التفاعل الأعلى وليس الحجم فقط." },
    { id: "funnels", title: "منشئ القمع", desc: "بناء قمع تحويل متعدد المراحل وتحديد مكان التسرب.", advice: "عالج مرحلة واحدة حرجة كل مرة ثم أعد القياس بعد النشر." },
    { id: "ux", title: "ذكاء تجربة المستخدم", desc: "مراجعة مشاكل تجربة المستخدم ودرجات الجودة لاكتشاف نقاط الاحتكاك.", advice: "ابدأ بالمشاكل المؤثرة على صفحات التحويل الرئيسية." },
    { id: "custom_events", title: "الأحداث المخصصة", desc: "تتبع أفعال عمل خاصة مثل signup_click و checkout_start و form_submit.", advice: "وحّد أسماء الأحداث واجعلها مرتبطة بالفعل لتفادي تضارب التقارير." },
    { id: "identities", title: "الهويات", desc: "ربط النشاط المجهول بالمستخدم المعروف عند توفر الهوية.", advice: "افعل الربط بعد موافقة المستخدم وتسجيل الدخول لتحليل دورة حياة أدق." },
    { id: "companies", title: "الشركات", desc: "عرض بيانات الزيارات على مستوى الشركة لحالات B2B.", advice: "حوّل زيارات الشركات ذات النية العالية مباشرة إلى متابعة مبيعات." },
    { id: "exports", title: "التصدير", desc: "تصدير بيانات التحليلات للتحليل الخارجي أو المشاركة.", advice: "استخدم التصدير المجدول للتقارير المتكررة وتقليل العمل اليدوي." },
    { id: "settings", title: "الإعدادات", desc: "إدارة الملف الشخصي والإشعارات والنطاقات والأمان والفوترة.", advice: "فعّل التحقق بخطوتين لكل المدراء وراقب نقاط webhooks باستمرار." },
  ] as FeatureDoc[],
  metrics: [
    { name: "الزوار", meaning: "عدد الزوار الفريدين خلال الفترة الزمنية المختارة.", advice: "ارتفاع الزوار مع جودة ثابتة غالباً مؤشر اكتساب صحي." },
    { name: "الجلسات", meaning: "عدد جلسات التصفح المنفصلة التي أنشأها المستخدمون.", advice: "نسبة جيدة بين الزوار والجلسات قد تعني عودة الزائر أكثر من مرة." },
    { name: "مشاهدات الصفحات", meaning: "إجمالي أحداث مشاهدة الصفحة المسجلة.", advice: "اقرأها مع عدد الزوار لفهم عمق الاستخدام وليس الوصول فقط." },
    { name: "معدل الارتداد", meaning: "نسبة الجلسات التي انتهت بعد صفحة واحدة فقط.", advice: "ليس دائماً سيئاً؛ قيّمه حسب هدف الصفحة ومصدر الزيارة." },
    { name: "متوسط مدة الجلسة", meaning: "متوسط الوقت الذي يقضيه المستخدم داخل الجلسة.", advice: "اربطه بنتائج التحويل؛ المدة الأطول ليست الأفضل دائماً." },
    { name: "أفضل الصفحات", meaning: "الصفحات صاحبة أعلى حجم مشاهدة.", advice: "هذه أولويات التحسين في تجربة المستخدم ورسائل التحويل." },
    { name: "أفضل الدول", meaning: "توزيع الزيارات جغرافياً حسب الدولة.", advice: "خصص اللغة والعروض للأسواق الأعلى نشاطاً." },
    { name: "أفضل الأجهزة", meaning: "توزيع الزيارات بين كمبيوتر وموبايل وتابلت.", advice: "إذا كان الموبايل الأعلى، اختبر النماذج والشراء على الشاشات الصغيرة أولاً." },
  ] as MetricDoc[],
};

export async function generateMetadata({ params }: { params: { locale: string } }): Promise<Metadata> {
  const content = params.locale === "ar" ? AR : EN;

  return {
    title: content.pageTitle,
    description: content.pageDescription,
    alternates: {
      canonical: `/${params.locale}/docs`,
      languages: { en: "/en/docs", ar: "/ar/docs" },
    },
  };
}

export default function DocsPage({ params }: { params: { locale: string } }) {
  const locale = params.locale;
  const content = locale === "ar" ? AR : EN;

  return (
    <>
      <Navbar />
      <main className="pt-24 pb-20">
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="rounded-3xl border border-outline-variant/20 bg-surface-container/40 p-8 sm:p-10">
            <Badge className="mb-4 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-300/20">
              <BookOpen className="w-3.5 h-3.5 ltr:mr-2 rtl:ml-2" />
              {content.heroBadge}
            </Badge>
            <h1 className="text-4xl sm:text-5xl font-black tracking-tight text-on-surface">{content.heroTitle}</h1>
            <p className="mt-4 text-on-surface-variant max-w-3xl text-base sm:text-lg">{content.heroSubtitle}</p>
            <div className="mt-5 inline-flex items-center gap-2 rounded-xl bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 px-3 py-2 text-sm">
              <ShieldCheck className="w-4 h-4" />
              {content.noAuth}
            </div>
          </div>
        </section>

        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10 grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-2 rounded-2xl border border-outline-variant/20 bg-surface-container/30 p-6">
            <h2 className="text-2xl font-black text-on-surface flex items-center gap-2">
              <Radar className="w-5 h-5 text-indigo-500" />
              {content.quickStartTitle}
            </h2>
            <ol className="mt-4 space-y-3">
              {content.quickStart.map((step, index) => (
                <li key={index} className="flex items-start gap-3 text-sm text-on-surface-variant">
                  <span className="w-6 h-6 shrink-0 rounded-full bg-indigo-500/15 text-indigo-700 dark:text-indigo-300 text-xs font-bold flex items-center justify-center mt-0.5">{index + 1}</span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </div>

          <div className="rounded-2xl border border-outline-variant/20 bg-surface-container/30 p-6">
            <h2 className="text-xl font-black text-on-surface flex items-center gap-2">
              <Lightbulb className="w-5 h-5 text-amber-500" />
              {content.tipsTitle}
            </h2>
            <ul className="mt-4 space-y-3 text-sm text-on-surface-variant">
              {content.tips.map((tip, i) => (
                <li key={i} className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500 mt-0.5 shrink-0" />
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10">
          <h2 className="text-3xl font-black tracking-tight text-on-surface mb-5">{content.featuresTitle}</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {content.features.map((feature) => (
              <article key={feature.id} className="rounded-2xl border border-outline-variant/20 bg-surface-container/30 p-5">
                <h3 className="text-lg font-black text-on-surface">{feature.title}</h3>
                <p className="mt-2 text-sm text-on-surface-variant">{feature.desc}</p>
                <div className="mt-3 rounded-lg bg-indigo-500/10 text-indigo-700 dark:text-indigo-300 p-3 text-sm">
                  <span className="font-semibold">{content.adviceLabel}:</span> {feature.advice}
                </div>
              </article>
            ))}
          </div>
        </section>

        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-12">
          <h2 className="text-3xl font-black tracking-tight text-on-surface mb-5 flex items-center gap-2">
            <Gauge className="w-6 h-6 text-violet-500" />
            {content.metricsTitle}
          </h2>
          <div className="overflow-hidden rounded-2xl border border-outline-variant/20 bg-surface-container/30">
            <div className="grid grid-cols-1 md:grid-cols-3 bg-surface-container-high/40 text-sm font-bold text-on-surface px-4 py-3">
              <div>{content.metricNameLabel}</div>
              <div>{content.metricMeaningLabel}</div>
              <div>{content.metricAdviceLabel}</div>
            </div>
            {content.metrics.map((metric, index) => (
              <div key={metric.name} className={`grid grid-cols-1 md:grid-cols-3 gap-3 px-4 py-4 text-sm ${index % 2 === 0 ? "bg-transparent" : "bg-surface-container-high/20"}`}>
                <div className="font-semibold text-on-surface">{metric.name}</div>
                <div className="text-on-surface-variant">{metric.meaning}</div>
                <div className="text-on-surface-variant">{metric.advice}</div>
              </div>
            ))}
          </div>
        </section>

        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-12">
          <div className="rounded-2xl border border-outline-variant/20 bg-surface-container/30 p-6 sm:p-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <h2 className="text-2xl font-black text-on-surface">{content.ctaTitle}</h2>
              <p className="text-sm text-on-surface-variant mt-1">{content.ctaText}</p>
            </div>
            <Link href={`/${locale}/auth/register`}>
              <Button className="bg-indigo-500 hover:bg-indigo-400 text-white">
                {content.ctaButton}
                <ArrowRight className="w-4 h-4 ltr:ml-2 rtl:mr-2" />
              </Button>
            </Link>
          </div>
        </section>
      </main>
      <Footer locale={locale} />
    </>
  );
}
